### ISSUE TITLE
FATAL EXCEPTION: main                                                                                                     Process: com.benjaminwan.ocr.java, PID: 8751

### ISSUE THREAD

**Issue by Cui0526** [RapidAI/RapidOcrAndroidOnnx#12]
我想下载的project源码但是运行app就会出现闪退  在logcat上 报错FATAL EXCEPTION: main
                                                                                                    Process: com.benjaminwan.ocr.java, PID: 8751
                                                                                                    java.lang.UnsatisfiedLinkError: dlopen failed: library "libonnxruntime.so" not found: needed by /data/app/~~WHeXOFKSY969Vc_CLKzRxA==/com.benjaminwan.ocr.java-gt4owbgoHcLqc4aWx0HN5Q==/lib/x86_64/libRapidOcr.so in namespace classloader-namespace
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1661)
                                                                                                    	at com.benjaminwan.ocrlibrary.OcrEngine.<init>(OcrEngine.kt:13)
                                                                                                    	at com.benjaminwan.ocr.java.MainActivity.onCreate(MainActivity.java:65)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8342)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8321)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7924)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by benjaminwan** [comment]
libonnxruntime.so缺失。
因为你没提供你的操作步骤、运行环境、开发环境等相关信息，所以这问题还是得靠你自己解决。
建议参照编译说明，下载Release中的Project压缩包与你现在clone的源码对比一下，用Release中的apk解压后跟你自己生成的apk对比一下，跑一下Release提供的apk看看log有什么不一样，再试一试。

**Comment by Cui0526** [comment]
> libonnxruntime.so缺失。 因为你没提供你的操作步骤、运行环境、开发环境等相关信息，所以这问题还是得靠你自己解决。 建议参照编译说明，下载Release中的Project压缩包与你现在clone的源码对比一下，用Release中的apk解压后跟你自己生成的apk对比一下，跑一下Release提供的apk看看log有什么不一样，再试一试。

我下载的就是Release中的Project压缩包 最新版的  然后解压   然后直接导入到  as中，然后运行   接着无论是安卓手机还是虚拟机  都会闪退

**Comment by benjaminwan** [comment]
> 我下载的就是Release中的Project压缩包 最新版的 然后解压 然后直接导入到 as中，然后运行 接着无论是安卓手机还是虚拟机 都会闪退

如果下载Release中的apk来跑也闪退，那就只能请你自己解决(最新版android 15 ，google对原生代码改成了16K Page Size，或许有影响？ )，这个项目发布于5年前，现已不再活跃开发，如果你有任何改进的代码，也欢迎贡献pr。

**Comment by benjaminwan** [comment]
我这里能正常运行的环境是windows 10 22H2， x86_64架构。
Android虚拟机是As自带的，Android 10 x86_64。
AS版本如下：Android Studio Koala Feature Drop | 2024.1.2 Patch 1


![Screenshot_1729761548](https://github.com/user-attachments/assets/d75ec455-41ad-4a06-b163-c51bdcaea28f)
![ASversion](https://github.com/user-attachments/assets/3cf897e5-8e4e-4ca9-aff8-c248f8a2439e)

**Comment by benjaminwan** [comment]
最后，这个项目含有C++代码，C++代码由cmake管理，正常来说Android Studio会自己下载NDK和Cmake。因为墙的存在(或许某些情况下AS无法下载对应的工具链)，能访问这里的人应该不会缺少相关的知识，就默认不再多说明了。
以下是我的配置，仅供参考：
![NDK](https://github.com/user-attachments/assets/2048e8dd-1150-4044-af96-6c7fe845952f)
